package com.yyk.sz.zhzy.jcsjxt.entity;

import java.math.BigDecimal;
import java.util.Date;

public class JCSJMedicalCare {

    private String medicalcarecode;

    private String uuid;

    private String medicalcarename;

    private String medicalcarename2;


    private String pinyincode;

    private Integer unitcode;

    private String unitname;

    private BigDecimal singleprice;

    private String hismedicalcarecode;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_MedicalCare
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public JCSJMedicalCare() {
        super();
    }

    public String getMedicalcarename2() {
        return medicalcarename2;
    }

    public void setMedicalcarename2(String medicalcarename2) {
        this.medicalcarename2 = medicalcarename2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_MedicalCare.MedicalCareCode
     *
     * @return the value of Gy_MedicalCare.MedicalCareCode
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public String getMedicalcarecode() {
        return medicalcarecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_MedicalCare.MedicalCareCode
     *
     * @param medicalcarecode the value for Gy_MedicalCare.MedicalCareCode
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public void setMedicalcarecode(String medicalcarecode) {
        this.medicalcarecode = medicalcarecode == null ? null : medicalcarecode.trim();
    }

    public String getUnitname() {
        return unitname;
    }

    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_MedicalCare.UUID
     *
     * @return the value of Gy_MedicalCare.UUID
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_MedicalCare.UUID
     *
     * @param uuid the value for Gy_MedicalCare.UUID
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_MedicalCare.MedicalCareName
     *
     * @return the value of Gy_MedicalCare.MedicalCareName
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public String getMedicalcarename() {
        return medicalcarename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_MedicalCare.MedicalCareName
     *
     * @param medicalcarename the value for Gy_MedicalCare.MedicalCareName
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public void setMedicalcarename(String medicalcarename) {
        this.medicalcarename = medicalcarename == null ? null : medicalcarename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_MedicalCare.PinYinCode
     *
     * @return the value of Gy_MedicalCare.PinYinCode
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public String getPinyincode() {
        return pinyincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_MedicalCare.PinYinCode
     *
     * @param pinyincode the value for Gy_MedicalCare.PinYinCode
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public void setPinyincode(String pinyincode) {
        this.pinyincode = pinyincode == null ? null : pinyincode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_MedicalCare.UnitCode
     *
     * @return the value of Gy_MedicalCare.UnitCode
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public Integer getUnitcode() {
        return unitcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_MedicalCare.UnitCode
     *
     * @param unitcode the value for Gy_MedicalCare.UnitCode
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public void setUnitcode(Integer unitcode) {
        this.unitcode = unitcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_MedicalCare.SinglePrice
     *
     * @return the value of Gy_MedicalCare.SinglePrice
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public BigDecimal getSingleprice() {
        return singleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_MedicalCare.SinglePrice
     *
     * @param singleprice the value for Gy_MedicalCare.SinglePrice
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public void setSingleprice(BigDecimal singleprice) {
        this.singleprice = singleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_MedicalCare.HISMedicalCareCode
     *
     * @return the value of Gy_MedicalCare.HISMedicalCareCode
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public String getHismedicalcarecode() {
        return hismedicalcarecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_MedicalCare.HISMedicalCareCode
     *
     * @param hismedicalcarecode the value for Gy_MedicalCare.HISMedicalCareCode
     *
     * @mbggenerated Thu Dec 20 19:12:21 CST 2018
     */
    public void setHismedicalcarecode(String hismedicalcarecode) {
        this.hismedicalcarecode = hismedicalcarecode == null ? null : hismedicalcarecode.trim();
    }

}