package com.yyk.sz.zhzy.jcsjxt.entity;

// 药品剂型
public class JCSJDosage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Gy_Dosage.DosageCode
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    private Integer dosagecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Gy_Dosage.UUID
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Gy_Dosage.DosageName
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    private String dosagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Gy_Dosage.PinYinCode
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    private String pinyincode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_Dosage
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public JCSJDosage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_Dosage.DosageCode
     *
     * @return the value of Gy_Dosage.DosageCode
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public Integer getDosagecode() {
        return dosagecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_Dosage.DosageCode
     *
     * @param dosagecode the value for Gy_Dosage.DosageCode
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public void setDosagecode(Integer dosagecode) {
        this.dosagecode = dosagecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_Dosage.UUID
     *
     * @return the value of Gy_Dosage.UUID
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_Dosage.UUID
     *
     * @param uuid the value for Gy_Dosage.UUID
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_Dosage.DosageName
     *
     * @return the value of Gy_Dosage.DosageName
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public String getDosagename() {
        return dosagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_Dosage.DosageName
     *
     * @param dosagename the value for Gy_Dosage.DosageName
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public void setDosagename(String dosagename) {
        this.dosagename = dosagename == null ? null : dosagename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_Dosage.PinYinCode
     *
     * @return the value of Gy_Dosage.PinYinCode
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public String getPinyincode() {
        return pinyincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_Dosage.PinYinCode
     *
     * @param pinyincode the value for Gy_Dosage.PinYinCode
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public void setPinyincode(String pinyincode) {
        this.pinyincode = pinyincode == null ? null : pinyincode.trim();
    }

}