package com.yyk.sz.zhzy.jcsjxt.entity;

public class JCSJUsedPhrases {

    private String uuid;

    private Integer usedphrasestype;

    private String usedphrasesname;

    private Integer usedphrasestype2;

    private String usedphrasesname2;



    private String pinyincode;


    private String usedphrasescontent;


    private String remarksub;

    private String deptcode;
    private String deptname;

    public JCSJUsedPhrases() {
        super();
    }

    public Integer getUsedphrasestype2() {
        return usedphrasestype2;
    }

    public void setUsedphrasestype2(Integer usedphrasestype2) {
        this.usedphrasestype2 = usedphrasestype2;
    }

    public String getUsedphrasesname2() {
        return usedphrasesname2;
    }

    public void setUsedphrasesname2(String usedphrasesname2) {
        this.usedphrasesname2 = usedphrasesname2;
    }

    public String getDeptname() {
        return deptname;
    }

    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    public String getUuid() {
        return uuid;
    }


    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }


    public Integer getUsedphrasestype() {
        return usedphrasestype;
    }


    public void setUsedphrasestype(Integer usedphrasestype) {
        this.usedphrasestype = usedphrasestype;
    }

    public String getUsedphrasesname() {
        return usedphrasesname;
    }

    public void setUsedphrasesname(String usedphrasesname) {
        this.usedphrasesname = usedphrasesname == null ? null : usedphrasesname.trim();
    }

    public String getPinyincode() {
        return pinyincode;
    }

    public void setPinyincode(String pinyincode) {
        this.pinyincode = pinyincode == null ? null : pinyincode.trim();
    }

    public String getUsedphrasescontent() {
        return usedphrasescontent;
    }

    public void setUsedphrasescontent(String usedphrasescontent) {
        this.usedphrasescontent = usedphrasescontent == null ? null : usedphrasescontent.trim();
    }

    public String getRemarksub() {
        return remarksub;
    }

    public void setRemarksub(String remarksub) {
        this.remarksub = remarksub == null ? null : remarksub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_UsedPhrases.DeptCode
     *
     * @return the value of CM_UsedPhrases.DeptCode
     * @mbggenerated Thu Dec 20 10:18:11 CST 2018
     */
    public String getDeptcode() {
        return deptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_UsedPhrases.DeptCode
     *
     * @param deptcode the value for CM_UsedPhrases.DeptCode
     * @mbggenerated Thu Dec 20 10:18:11 CST 2018
     */
    public void setDeptcode(String deptcode) {
        this.deptcode = deptcode == null ? null : deptcode.trim();
    }
}