package com.yyk.sz.zhzy.jcsjxt.entity;

public class JCSJSummaryItem {

    private String summarycode;

    private String uuid;

    private String summaryname;

    private String summaryname2;

    private String pinyincode;


    private String remark;


    private String hiscode;

    private Integer detailitemflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_SummaryItem
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public JCSJSummaryItem() {
        super();
    }

    public String getSummaryname2() {
        return summaryname2;
    }

    public void setSummaryname2(String summaryname2) {
        this.summaryname2 = summaryname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_SummaryItem.SummaryCode
     *
     * @return the value of Gy_SummaryItem.SummaryCode
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public String getSummarycode() {
        return summarycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_SummaryItem.SummaryCode
     *
     * @param summarycode the value for Gy_SummaryItem.SummaryCode
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public void setSummarycode(String summarycode) {
        this.summarycode = summarycode == null ? null : summarycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_SummaryItem.UUID
     *
     * @return the value of Gy_SummaryItem.UUID
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_SummaryItem.UUID
     *
     * @param uuid the value for Gy_SummaryItem.UUID
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_SummaryItem.SummaryName
     *
     * @return the value of Gy_SummaryItem.SummaryName
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public String getSummaryname() {
        return summaryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_SummaryItem.SummaryName
     *
     * @param summaryname the value for Gy_SummaryItem.SummaryName
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public void setSummaryname(String summaryname) {
        this.summaryname = summaryname == null ? null : summaryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_SummaryItem.PinYinCode
     *
     * @return the value of Gy_SummaryItem.PinYinCode
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public String getPinyincode() {
        return pinyincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_SummaryItem.PinYinCode
     *
     * @param pinyincode the value for Gy_SummaryItem.PinYinCode
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public void setPinyincode(String pinyincode) {
        this.pinyincode = pinyincode == null ? null : pinyincode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_SummaryItem.Remark
     *
     * @return the value of Gy_SummaryItem.Remark
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_SummaryItem.Remark
     *
     * @param remark the value for Gy_SummaryItem.Remark
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_SummaryItem.HISCode
     *
     * @return the value of Gy_SummaryItem.HISCode
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public String getHiscode() {
        return hiscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_SummaryItem.HISCode
     *
     * @param hiscode the value for Gy_SummaryItem.HISCode
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public void setHiscode(String hiscode) {
        this.hiscode = hiscode == null ? null : hiscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_SummaryItem.DetailItemFlag
     *
     * @return the value of Gy_SummaryItem.DetailItemFlag
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public Integer getDetailitemflag() {
        return detailitemflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_SummaryItem.DetailItemFlag
     *
     * @param detailitemflag the value for Gy_SummaryItem.DetailItemFlag
     *
     * @mbggenerated Fri Dec 21 13:32:28 CST 2018
     */
    public void setDetailitemflag(Integer detailitemflag) {
        this.detailitemflag = detailitemflag;
    }

}