package com.yyk.sz.zhzy.jcsjxt.entity;

import java.util.List;

public class JCSJDetailItem {

    private String detailitemcode;


    private String uuid;

    private String detailitemname;

    private String detailitemname2;

    private String summaryname;

    private String pinyincode;

    private String summarycode;

    private String remark;

    private String hisdetailitemcode;

    private Integer detailitemflag;

    private List<JCSJDetailItemSub> JCSJDetailItemSubs;



    public JCSJDetailItem() {
        super();
    }


    public String getDetailitemcode() {
        return detailitemcode;
    }

    public String getSummaryname() {
        return summaryname;
    }

    public void setSummaryname(String summaryname) {
        this.summaryname = summaryname;
    }

    public List<JCSJDetailItemSub> getJCSJDetailItemSubs() {
        return JCSJDetailItemSubs;
    }

    public void setJCSJDetailItemSubs(List<JCSJDetailItemSub> JCSJDetailItemSubs) {
        this.JCSJDetailItemSubs = JCSJDetailItemSubs;
    }

    public String getDetailitemname2() {
        return detailitemname2;
    }

    public void setDetailitemname2(String detailitemname2) {
        this.detailitemname2 = detailitemname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_DetailItem.DetailItemCode
     *
     * @param detailitemcode the value for Gy_DetailItem.DetailItemCode
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public void setDetailitemcode(String detailitemcode) {
        this.detailitemcode = detailitemcode == null ? null : detailitemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_DetailItem.UUID
     *
     * @return the value of Gy_DetailItem.UUID
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_DetailItem.UUID
     *
     * @param uuid the value for Gy_DetailItem.UUID
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_DetailItem.DetailItemName
     *
     * @return the value of Gy_DetailItem.DetailItemName
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public String getDetailitemname() {
        return detailitemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_DetailItem.DetailItemName
     *
     * @param detailitemname the value for Gy_DetailItem.DetailItemName
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public void setDetailitemname(String detailitemname) {
        this.detailitemname = detailitemname == null ? null : detailitemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_DetailItem.PinYinCode
     *
     * @return the value of Gy_DetailItem.PinYinCode
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public String getPinyincode() {
        return pinyincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_DetailItem.PinYinCode
     *
     * @param pinyincode the value for Gy_DetailItem.PinYinCode
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public void setPinyincode(String pinyincode) {
        this.pinyincode = pinyincode == null ? null : pinyincode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_DetailItem.SummaryCode
     *
     * @return the value of Gy_DetailItem.SummaryCode
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public String getSummarycode() {
        return summarycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_DetailItem.SummaryCode
     *
     * @param summarycode the value for Gy_DetailItem.SummaryCode
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public void setSummarycode(String summarycode) {
        this.summarycode = summarycode == null ? null : summarycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_DetailItem.Remark
     *
     * @return the value of Gy_DetailItem.Remark
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_DetailItem.Remark
     *
     * @param remark the value for Gy_DetailItem.Remark
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_DetailItem.HISDetailItemCode
     *
     * @return the value of Gy_DetailItem.HISDetailItemCode
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public String getHisdetailitemcode() {
        return hisdetailitemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_DetailItem.HISDetailItemCode
     *
     * @param hisdetailitemcode the value for Gy_DetailItem.HISDetailItemCode
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public void setHisdetailitemcode(String hisdetailitemcode) {
        this.hisdetailitemcode = hisdetailitemcode == null ? null : hisdetailitemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_DetailItem.DetailItemFlag
     *
     * @return the value of Gy_DetailItem.DetailItemFlag
     *
     * @mbggenerated Fri Dec 21 15:50:39 CST 2018
     */
    public Integer getDetailitemflag() {
        return detailitemflag;
    }


    public void setDetailitemflag(Integer detailitemflag) {
        this.detailitemflag = detailitemflag;
    }

}