package com.yyk.sz.zhzy.jcsjxt.entity;

//药品服法
public class JCSJDrugWay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Gy_DrugWay.DrugWayCode
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    private Integer drugwaycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Gy_DrugWay.UUID
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Gy_DrugWay.DrugWayName
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    private String drugwayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Gy_DrugWay.PinYinCode
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    private String pinyincode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_DrugWay
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public JCSJDrugWay() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_DrugWay.DrugWayCode
     *
     * @return the value of Gy_DrugWay.DrugWayCode
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public Integer getDrugwaycode() {
        return drugwaycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_DrugWay.DrugWayCode
     *
     * @param drugwaycode the value for Gy_DrugWay.DrugWayCode
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public void setDrugwaycode(Integer drugwaycode) {
        this.drugwaycode = drugwaycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_DrugWay.UUID
     *
     * @return the value of Gy_DrugWay.UUID
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_DrugWay.UUID
     *
     * @param uuid the value for Gy_DrugWay.UUID
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_DrugWay.DrugWayName
     *
     * @return the value of Gy_DrugWay.DrugWayName
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public String getDrugwayname() {
        return drugwayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_DrugWay.DrugWayName
     *
     * @param drugwayname the value for Gy_DrugWay.DrugWayName
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public void setDrugwayname(String drugwayname) {
        this.drugwayname = drugwayname == null ? null : drugwayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Gy_DrugWay.PinYinCode
     *
     * @return the value of Gy_DrugWay.PinYinCode
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public String getPinyincode() {
        return pinyincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Gy_DrugWay.PinYinCode
     *
     * @param pinyincode the value for Gy_DrugWay.PinYinCode
     *
     * @mbggenerated Thu Dec 20 13:24:39 CST 2018
     */
    public void setPinyincode(String pinyincode) {
        this.pinyincode = pinyincode == null ? null : pinyincode.trim();
    }

}