package com.yyk.sz.zhzy.system.core.entity;

import java.util.Date;

public class SysDictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.code
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.name
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.type
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.sortNo
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Integer sortno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.remark
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.parentId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Date syscreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String syscreateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Date sysupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String sysupdateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Integer versionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String sysdelflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public SysDictionary(String uuid, String code, String name, String type, Integer sortno, String remark, String parentid, Date syscreatedate, String syscreateby, Date sysupdatedate, String sysupdateby, Integer versionnum, String sysdelflag) {
        this.uuid = uuid;
        this.code = code;
        this.name = name;
        this.type = type;
        this.sortno = sortno;
        this.remark = remark;
        this.parentid = parentid;
        this.syscreatedate = syscreatedate;
        this.syscreateby = syscreateby;
        this.sysupdatedate = sysupdatedate;
        this.sysupdateby = sysupdateby;
        this.versionnum = versionnum;
        this.sysdelflag = sysdelflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public SysDictionary() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.UUID
     *
     * @return the value of sys_dictionary.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.UUID
     *
     * @param uuid the value for sys_dictionary.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.code
     *
     * @return the value of sys_dictionary.code
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.code
     *
     * @param code the value for sys_dictionary.code
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.name
     *
     * @return the value of sys_dictionary.name
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.name
     *
     * @param name the value for sys_dictionary.name
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.type
     *
     * @return the value of sys_dictionary.type
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.type
     *
     * @param type the value for sys_dictionary.type
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.sortNo
     *
     * @return the value of sys_dictionary.sortNo
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Integer getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.sortNo
     *
     * @param sortno the value for sys_dictionary.sortNo
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSortno(Integer sortno) {
        this.sortno = sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.remark
     *
     * @return the value of sys_dictionary.remark
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.remark
     *
     * @param remark the value for sys_dictionary.remark
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.parentId
     *
     * @return the value of sys_dictionary.parentId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.parentId
     *
     * @param parentid the value for sys_dictionary.parentId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.SysCreateDate
     *
     * @return the value of sys_dictionary.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Date getSyscreatedate() {
        return syscreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.SysCreateDate
     *
     * @param syscreatedate the value for sys_dictionary.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSyscreatedate(Date syscreatedate) {
        this.syscreatedate = syscreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.SysCreateBy
     *
     * @return the value of sys_dictionary.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSyscreateby() {
        return syscreateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.SysCreateBy
     *
     * @param syscreateby the value for sys_dictionary.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSyscreateby(String syscreateby) {
        this.syscreateby = syscreateby == null ? null : syscreateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.SysUpdateDate
     *
     * @return the value of sys_dictionary.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Date getSysupdatedate() {
        return sysupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.SysUpdateDate
     *
     * @param sysupdatedate the value for sys_dictionary.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysupdatedate(Date sysupdatedate) {
        this.sysupdatedate = sysupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.SysUpdateBy
     *
     * @return the value of sys_dictionary.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSysupdateby() {
        return sysupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.SysUpdateBy
     *
     * @param sysupdateby the value for sys_dictionary.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysupdateby(String sysupdateby) {
        this.sysupdateby = sysupdateby == null ? null : sysupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.VersionNum
     *
     * @return the value of sys_dictionary.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Integer getVersionnum() {
        return versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.VersionNum
     *
     * @param versionnum the value for sys_dictionary.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setVersionnum(Integer versionnum) {
        this.versionnum = versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.SysDelFlag
     *
     * @return the value of sys_dictionary.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSysdelflag() {
        return sysdelflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.SysDelFlag
     *
     * @param sysdelflag the value for sys_dictionary.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysdelflag(String sysdelflag) {
        this.sysdelflag = sysdelflag == null ? null : sysdelflag.trim();
    }
}