package com.yyk.sz.zhzy.system.core.entity;

import java.util.Date;

public class SysDatascope {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.sysCode
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String syscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.name
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.targetType
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String targettype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.target
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.type
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.value
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.conditionType
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String conditiontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Date syscreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String syscreateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Date sysupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String sysupdateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Integer versionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_datascope.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String sysdelflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_datascope
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public SysDatascope(String uuid, String syscode, String name, String targettype, String target, String type, String value, String conditiontype, Date syscreatedate, String syscreateby, Date sysupdatedate, String sysupdateby, Integer versionnum, String sysdelflag) {
        this.uuid = uuid;
        this.syscode = syscode;
        this.name = name;
        this.targettype = targettype;
        this.target = target;
        this.type = type;
        this.value = value;
        this.conditiontype = conditiontype;
        this.syscreatedate = syscreatedate;
        this.syscreateby = syscreateby;
        this.sysupdatedate = sysupdatedate;
        this.sysupdateby = sysupdateby;
        this.versionnum = versionnum;
        this.sysdelflag = sysdelflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_datascope
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public SysDatascope() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.UUID
     *
     * @return the value of sys_datascope.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.UUID
     *
     * @param uuid the value for sys_datascope.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.sysCode
     *
     * @return the value of sys_datascope.sysCode
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSyscode() {
        return syscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.sysCode
     *
     * @param syscode the value for sys_datascope.sysCode
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSyscode(String syscode) {
        this.syscode = syscode == null ? null : syscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.name
     *
     * @return the value of sys_datascope.name
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.name
     *
     * @param name the value for sys_datascope.name
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.targetType
     *
     * @return the value of sys_datascope.targetType
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getTargettype() {
        return targettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.targetType
     *
     * @param targettype the value for sys_datascope.targetType
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setTargettype(String targettype) {
        this.targettype = targettype == null ? null : targettype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.target
     *
     * @return the value of sys_datascope.target
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.target
     *
     * @param target the value for sys_datascope.target
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.type
     *
     * @return the value of sys_datascope.type
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.type
     *
     * @param type the value for sys_datascope.type
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.value
     *
     * @return the value of sys_datascope.value
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.value
     *
     * @param value the value for sys_datascope.value
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.conditionType
     *
     * @return the value of sys_datascope.conditionType
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getConditiontype() {
        return conditiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.conditionType
     *
     * @param conditiontype the value for sys_datascope.conditionType
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setConditiontype(String conditiontype) {
        this.conditiontype = conditiontype == null ? null : conditiontype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.SysCreateDate
     *
     * @return the value of sys_datascope.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Date getSyscreatedate() {
        return syscreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.SysCreateDate
     *
     * @param syscreatedate the value for sys_datascope.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSyscreatedate(Date syscreatedate) {
        this.syscreatedate = syscreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.SysCreateBy
     *
     * @return the value of sys_datascope.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSyscreateby() {
        return syscreateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.SysCreateBy
     *
     * @param syscreateby the value for sys_datascope.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSyscreateby(String syscreateby) {
        this.syscreateby = syscreateby == null ? null : syscreateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.SysUpdateDate
     *
     * @return the value of sys_datascope.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Date getSysupdatedate() {
        return sysupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.SysUpdateDate
     *
     * @param sysupdatedate the value for sys_datascope.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysupdatedate(Date sysupdatedate) {
        this.sysupdatedate = sysupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.SysUpdateBy
     *
     * @return the value of sys_datascope.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSysupdateby() {
        return sysupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.SysUpdateBy
     *
     * @param sysupdateby the value for sys_datascope.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysupdateby(String sysupdateby) {
        this.sysupdateby = sysupdateby == null ? null : sysupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.VersionNum
     *
     * @return the value of sys_datascope.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Integer getVersionnum() {
        return versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.VersionNum
     *
     * @param versionnum the value for sys_datascope.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setVersionnum(Integer versionnum) {
        this.versionnum = versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_datascope.SysDelFlag
     *
     * @return the value of sys_datascope.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSysdelflag() {
        return sysdelflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_datascope.SysDelFlag
     *
     * @param sysdelflag the value for sys_datascope.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysdelflag(String sysdelflag) {
        this.sysdelflag = sysdelflag == null ? null : sysdelflag.trim();
    }
}