package com.yyk.sz.zhzy.system.core.entity;

import java.util.Date;
import java.util.List;

public class SysResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.code
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.name
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.sortNo
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Integer sortno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.bizsysId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String bizsysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.parentId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.level
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.abbName
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String abbname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Date syscreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String syscreateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Date sysupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String sysupdateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Integer versionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String sysdelflag;

    private List<SysResource> children;

    public List<SysResource> getChildren() {
        return children;
    }

    public void setChildren(List<SysResource> children) {
        this.children = children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public SysResource(String uuid, String code, String name, Integer sortno, String bizsysid, String parentid, Integer level, String abbname, Date syscreatedate, String syscreateby, Date sysupdatedate, String sysupdateby, Integer versionnum, String sysdelflag) {
        this.uuid = uuid;
        this.code = code;
        this.name = name;
        this.sortno = sortno;
        this.bizsysid = bizsysid;
        this.parentid = parentid;
        this.level = level;
        this.abbname = abbname;
        this.syscreatedate = syscreatedate;
        this.syscreateby = syscreateby;
        this.sysupdatedate = sysupdatedate;
        this.sysupdateby = sysupdateby;
        this.versionnum = versionnum;
        this.sysdelflag = sysdelflag;
    }

    public SysResource(String uuid, String parentid, String name) {
        this.uuid = uuid;
        this.parentid = parentid;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public SysResource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.UUID
     *
     * @return the value of sys_resource.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.UUID
     *
     * @param uuid the value for sys_resource.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.code
     *
     * @return the value of sys_resource.code
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.code
     *
     * @param code the value for sys_resource.code
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.name
     *
     * @return the value of sys_resource.name
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.name
     *
     * @param name the value for sys_resource.name
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.sortNo
     *
     * @return the value of sys_resource.sortNo
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Integer getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.sortNo
     *
     * @param sortno the value for sys_resource.sortNo
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSortno(Integer sortno) {
        this.sortno = sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.bizsysId
     *
     * @return the value of sys_resource.bizsysId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getBizsysid() {
        return bizsysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.bizsysId
     *
     * @param bizsysid the value for sys_resource.bizsysId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setBizsysid(String bizsysid) {
        this.bizsysid = bizsysid == null ? null : bizsysid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parentId
     *
     * @return the value of sys_resource.parentId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parentId
     *
     * @param parentid the value for sys_resource.parentId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.level
     *
     * @return the value of sys_resource.level
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.level
     *
     * @param level the value for sys_resource.level
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.abbName
     *
     * @return the value of sys_resource.abbName
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getAbbname() {
        return abbname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.abbName
     *
     * @param abbname the value for sys_resource.abbName
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setAbbname(String abbname) {
        this.abbname = abbname == null ? null : abbname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.SysCreateDate
     *
     * @return the value of sys_resource.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Date getSyscreatedate() {
        return syscreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.SysCreateDate
     *
     * @param syscreatedate the value for sys_resource.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSyscreatedate(Date syscreatedate) {
        this.syscreatedate = syscreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.SysCreateBy
     *
     * @return the value of sys_resource.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSyscreateby() {
        return syscreateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.SysCreateBy
     *
     * @param syscreateby the value for sys_resource.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSyscreateby(String syscreateby) {
        this.syscreateby = syscreateby == null ? null : syscreateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.SysUpdateDate
     *
     * @return the value of sys_resource.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Date getSysupdatedate() {
        return sysupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.SysUpdateDate
     *
     * @param sysupdatedate the value for sys_resource.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysupdatedate(Date sysupdatedate) {
        this.sysupdatedate = sysupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.SysUpdateBy
     *
     * @return the value of sys_resource.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSysupdateby() {
        return sysupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.SysUpdateBy
     *
     * @param sysupdateby the value for sys_resource.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysupdateby(String sysupdateby) {
        this.sysupdateby = sysupdateby == null ? null : sysupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.VersionNum
     *
     * @return the value of sys_resource.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Integer getVersionnum() {
        return versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.VersionNum
     *
     * @param versionnum the value for sys_resource.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setVersionnum(Integer versionnum) {
        this.versionnum = versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.SysDelFlag
     *
     * @return the value of sys_resource.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSysdelflag() {
        return sysdelflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.SysDelFlag
     *
     * @param sysdelflag the value for sys_resource.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysdelflag(String sysdelflag) {
        this.sysdelflag = sysdelflag == null ? null : sysdelflag.trim();
    }
}