package com.yyk.sz.zhzy.system.core.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysTenantExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public SysTenantExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andContactorIsNull() {
            addCriterion("contactor is null");
            return (Criteria) this;
        }

        public Criteria andContactorIsNotNull() {
            addCriterion("contactor is not null");
            return (Criteria) this;
        }

        public Criteria andContactorEqualTo(String value) {
            addCriterion("contactor =", value, "contactor");
            return (Criteria) this;
        }

        public Criteria andContactorNotEqualTo(String value) {
            addCriterion("contactor <>", value, "contactor");
            return (Criteria) this;
        }

        public Criteria andContactorGreaterThan(String value) {
            addCriterion("contactor >", value, "contactor");
            return (Criteria) this;
        }

        public Criteria andContactorGreaterThanOrEqualTo(String value) {
            addCriterion("contactor >=", value, "contactor");
            return (Criteria) this;
        }

        public Criteria andContactorLessThan(String value) {
            addCriterion("contactor <", value, "contactor");
            return (Criteria) this;
        }

        public Criteria andContactorLessThanOrEqualTo(String value) {
            addCriterion("contactor <=", value, "contactor");
            return (Criteria) this;
        }

        public Criteria andContactorLike(String value) {
            addCriterion("contactor like", value, "contactor");
            return (Criteria) this;
        }

        public Criteria andContactorNotLike(String value) {
            addCriterion("contactor not like", value, "contactor");
            return (Criteria) this;
        }

        public Criteria andContactorIn(List<String> values) {
            addCriterion("contactor in", values, "contactor");
            return (Criteria) this;
        }

        public Criteria andContactorNotIn(List<String> values) {
            addCriterion("contactor not in", values, "contactor");
            return (Criteria) this;
        }

        public Criteria andContactorBetween(String value1, String value2) {
            addCriterion("contactor between", value1, value2, "contactor");
            return (Criteria) this;
        }

        public Criteria andContactorNotBetween(String value1, String value2) {
            addCriterion("contactor not between", value1, value2, "contactor");
            return (Criteria) this;
        }

        public Criteria andPhonenoIsNull() {
            addCriterion("phoneNo is null");
            return (Criteria) this;
        }

        public Criteria andPhonenoIsNotNull() {
            addCriterion("phoneNo is not null");
            return (Criteria) this;
        }

        public Criteria andPhonenoEqualTo(String value) {
            addCriterion("phoneNo =", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoNotEqualTo(String value) {
            addCriterion("phoneNo <>", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoGreaterThan(String value) {
            addCriterion("phoneNo >", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoGreaterThanOrEqualTo(String value) {
            addCriterion("phoneNo >=", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoLessThan(String value) {
            addCriterion("phoneNo <", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoLessThanOrEqualTo(String value) {
            addCriterion("phoneNo <=", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoLike(String value) {
            addCriterion("phoneNo like", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoNotLike(String value) {
            addCriterion("phoneNo not like", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoIn(List<String> values) {
            addCriterion("phoneNo in", values, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoNotIn(List<String> values) {
            addCriterion("phoneNo not in", values, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoBetween(String value1, String value2) {
            addCriterion("phoneNo between", value1, value2, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoNotBetween(String value1, String value2) {
            addCriterion("phoneNo not between", value1, value2, "phoneno");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateIsNull() {
            addCriterion("SysCreateDate is null");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateIsNotNull() {
            addCriterion("SysCreateDate is not null");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateEqualTo(Date value) {
            addCriterion("SysCreateDate =", value, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateNotEqualTo(Date value) {
            addCriterion("SysCreateDate <>", value, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateGreaterThan(Date value) {
            addCriterion("SysCreateDate >", value, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("SysCreateDate >=", value, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateLessThan(Date value) {
            addCriterion("SysCreateDate <", value, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateLessThanOrEqualTo(Date value) {
            addCriterion("SysCreateDate <=", value, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateIn(List<Date> values) {
            addCriterion("SysCreateDate in", values, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateNotIn(List<Date> values) {
            addCriterion("SysCreateDate not in", values, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateBetween(Date value1, Date value2) {
            addCriterion("SysCreateDate between", value1, value2, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateNotBetween(Date value1, Date value2) {
            addCriterion("SysCreateDate not between", value1, value2, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyIsNull() {
            addCriterion("SysCreateBy is null");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyIsNotNull() {
            addCriterion("SysCreateBy is not null");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyEqualTo(String value) {
            addCriterion("SysCreateBy =", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyNotEqualTo(String value) {
            addCriterion("SysCreateBy <>", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyGreaterThan(String value) {
            addCriterion("SysCreateBy >", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyGreaterThanOrEqualTo(String value) {
            addCriterion("SysCreateBy >=", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyLessThan(String value) {
            addCriterion("SysCreateBy <", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyLessThanOrEqualTo(String value) {
            addCriterion("SysCreateBy <=", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyLike(String value) {
            addCriterion("SysCreateBy like", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyNotLike(String value) {
            addCriterion("SysCreateBy not like", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyIn(List<String> values) {
            addCriterion("SysCreateBy in", values, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyNotIn(List<String> values) {
            addCriterion("SysCreateBy not in", values, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyBetween(String value1, String value2) {
            addCriterion("SysCreateBy between", value1, value2, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyNotBetween(String value1, String value2) {
            addCriterion("SysCreateBy not between", value1, value2, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateIsNull() {
            addCriterion("SysUpdateDate is null");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateIsNotNull() {
            addCriterion("SysUpdateDate is not null");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateEqualTo(Date value) {
            addCriterion("SysUpdateDate =", value, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateNotEqualTo(Date value) {
            addCriterion("SysUpdateDate <>", value, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateGreaterThan(Date value) {
            addCriterion("SysUpdateDate >", value, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("SysUpdateDate >=", value, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateLessThan(Date value) {
            addCriterion("SysUpdateDate <", value, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateLessThanOrEqualTo(Date value) {
            addCriterion("SysUpdateDate <=", value, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateIn(List<Date> values) {
            addCriterion("SysUpdateDate in", values, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateNotIn(List<Date> values) {
            addCriterion("SysUpdateDate not in", values, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateBetween(Date value1, Date value2) {
            addCriterion("SysUpdateDate between", value1, value2, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateNotBetween(Date value1, Date value2) {
            addCriterion("SysUpdateDate not between", value1, value2, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyIsNull() {
            addCriterion("SysUpdateBy is null");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyIsNotNull() {
            addCriterion("SysUpdateBy is not null");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyEqualTo(String value) {
            addCriterion("SysUpdateBy =", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyNotEqualTo(String value) {
            addCriterion("SysUpdateBy <>", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyGreaterThan(String value) {
            addCriterion("SysUpdateBy >", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyGreaterThanOrEqualTo(String value) {
            addCriterion("SysUpdateBy >=", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyLessThan(String value) {
            addCriterion("SysUpdateBy <", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyLessThanOrEqualTo(String value) {
            addCriterion("SysUpdateBy <=", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyLike(String value) {
            addCriterion("SysUpdateBy like", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyNotLike(String value) {
            addCriterion("SysUpdateBy not like", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyIn(List<String> values) {
            addCriterion("SysUpdateBy in", values, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyNotIn(List<String> values) {
            addCriterion("SysUpdateBy not in", values, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyBetween(String value1, String value2) {
            addCriterion("SysUpdateBy between", value1, value2, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyNotBetween(String value1, String value2) {
            addCriterion("SysUpdateBy not between", value1, value2, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andVersionnumIsNull() {
            addCriterion("VersionNum is null");
            return (Criteria) this;
        }

        public Criteria andVersionnumIsNotNull() {
            addCriterion("VersionNum is not null");
            return (Criteria) this;
        }

        public Criteria andVersionnumEqualTo(Integer value) {
            addCriterion("VersionNum =", value, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumNotEqualTo(Integer value) {
            addCriterion("VersionNum <>", value, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumGreaterThan(Integer value) {
            addCriterion("VersionNum >", value, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("VersionNum >=", value, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumLessThan(Integer value) {
            addCriterion("VersionNum <", value, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumLessThanOrEqualTo(Integer value) {
            addCriterion("VersionNum <=", value, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumIn(List<Integer> values) {
            addCriterion("VersionNum in", values, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumNotIn(List<Integer> values) {
            addCriterion("VersionNum not in", values, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumBetween(Integer value1, Integer value2) {
            addCriterion("VersionNum between", value1, value2, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumNotBetween(Integer value1, Integer value2) {
            addCriterion("VersionNum not between", value1, value2, "versionnum");
            return (Criteria) this;
        }

        public Criteria andSysdelflagIsNull() {
            addCriterion("SysDelFlag is null");
            return (Criteria) this;
        }

        public Criteria andSysdelflagIsNotNull() {
            addCriterion("SysDelFlag is not null");
            return (Criteria) this;
        }

        public Criteria andSysdelflagEqualTo(String value) {
            addCriterion("SysDelFlag =", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagNotEqualTo(String value) {
            addCriterion("SysDelFlag <>", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagGreaterThan(String value) {
            addCriterion("SysDelFlag >", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagGreaterThanOrEqualTo(String value) {
            addCriterion("SysDelFlag >=", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagLessThan(String value) {
            addCriterion("SysDelFlag <", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagLessThanOrEqualTo(String value) {
            addCriterion("SysDelFlag <=", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagLike(String value) {
            addCriterion("SysDelFlag like", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagNotLike(String value) {
            addCriterion("SysDelFlag not like", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagIn(List<String> values) {
            addCriterion("SysDelFlag in", values, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagNotIn(List<String> values) {
            addCriterion("SysDelFlag not in", values, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagBetween(String value1, String value2) {
            addCriterion("SysDelFlag between", value1, value2, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagNotBetween(String value1, String value2) {
            addCriterion("SysDelFlag not between", value1, value2, "sysdelflag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_tenant
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 18 11:46:00 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_tenant
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}