package com.yyk.sz.zhzy.system.core.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public SysUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("account is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("account is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("account =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("account <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("account >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("account >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("account <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("account <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("account like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("account not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("account in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("account not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("account between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("account not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andHiscodeIsNull() {
            addCriterion("HISCode is null");
            return (Criteria) this;
        }

        public Criteria andHiscodeIsNotNull() {
            addCriterion("HISCode is not null");
            return (Criteria) this;
        }

        public Criteria andHiscodeEqualTo(String value) {
            addCriterion("HISCode =", value, "hiscode");
            return (Criteria) this;
        }

        public Criteria andHiscodeNotEqualTo(String value) {
            addCriterion("HISCode <>", value, "hiscode");
            return (Criteria) this;
        }

        public Criteria andHiscodeGreaterThan(String value) {
            addCriterion("HISCode >", value, "hiscode");
            return (Criteria) this;
        }

        public Criteria andHiscodeGreaterThanOrEqualTo(String value) {
            addCriterion("HISCode >=", value, "hiscode");
            return (Criteria) this;
        }

        public Criteria andHiscodeLessThan(String value) {
            addCriterion("HISCode <", value, "hiscode");
            return (Criteria) this;
        }

        public Criteria andHiscodeLessThanOrEqualTo(String value) {
            addCriterion("HISCode <=", value, "hiscode");
            return (Criteria) this;
        }

        public Criteria andHiscodeLike(String value) {
            addCriterion("HISCode like", value, "hiscode");
            return (Criteria) this;
        }

        public Criteria andHiscodeNotLike(String value) {
            addCriterion("HISCode not like", value, "hiscode");
            return (Criteria) this;
        }

        public Criteria andHiscodeIn(List<String> values) {
            addCriterion("HISCode in", values, "hiscode");
            return (Criteria) this;
        }

        public Criteria andHiscodeNotIn(List<String> values) {
            addCriterion("HISCode not in", values, "hiscode");
            return (Criteria) this;
        }

        public Criteria andHiscodeBetween(String value1, String value2) {
            addCriterion("HISCode between", value1, value2, "hiscode");
            return (Criteria) this;
        }

        public Criteria andHiscodeNotBetween(String value1, String value2) {
            addCriterion("HISCode not between", value1, value2, "hiscode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeIsNull() {
            addCriterion("organizationCode is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeIsNotNull() {
            addCriterion("organizationCode is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeEqualTo(String value) {
            addCriterion("organizationCode =", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeNotEqualTo(String value) {
            addCriterion("organizationCode <>", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeGreaterThan(String value) {
            addCriterion("organizationCode >", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeGreaterThanOrEqualTo(String value) {
            addCriterion("organizationCode >=", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeLessThan(String value) {
            addCriterion("organizationCode <", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeLessThanOrEqualTo(String value) {
            addCriterion("organizationCode <=", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeLike(String value) {
            addCriterion("organizationCode like", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeNotLike(String value) {
            addCriterion("organizationCode not like", value, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeIn(List<String> values) {
            addCriterion("organizationCode in", values, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeNotIn(List<String> values) {
            addCriterion("organizationCode not in", values, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeBetween(String value1, String value2) {
            addCriterion("organizationCode between", value1, value2, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationcodeNotBetween(String value1, String value2) {
            addCriterion("organizationCode not between", value1, value2, "organizationcode");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAliasIsNull() {
            addCriterion("alias is null");
            return (Criteria) this;
        }

        public Criteria andAliasIsNotNull() {
            addCriterion("alias is not null");
            return (Criteria) this;
        }

        public Criteria andAliasEqualTo(String value) {
            addCriterion("alias =", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotEqualTo(String value) {
            addCriterion("alias <>", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThan(String value) {
            addCriterion("alias >", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThanOrEqualTo(String value) {
            addCriterion("alias >=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThan(String value) {
            addCriterion("alias <", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThanOrEqualTo(String value) {
            addCriterion("alias <=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLike(String value) {
            addCriterion("alias like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotLike(String value) {
            addCriterion("alias not like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasIn(List<String> values) {
            addCriterion("alias in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotIn(List<String> values) {
            addCriterion("alias not in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasBetween(String value1, String value2) {
            addCriterion("alias between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotBetween(String value1, String value2) {
            addCriterion("alias not between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andPhonenoIsNull() {
            addCriterion("phoneNo is null");
            return (Criteria) this;
        }

        public Criteria andPhonenoIsNotNull() {
            addCriterion("phoneNo is not null");
            return (Criteria) this;
        }

        public Criteria andPhonenoEqualTo(String value) {
            addCriterion("phoneNo =", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoNotEqualTo(String value) {
            addCriterion("phoneNo <>", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoGreaterThan(String value) {
            addCriterion("phoneNo >", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoGreaterThanOrEqualTo(String value) {
            addCriterion("phoneNo >=", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoLessThan(String value) {
            addCriterion("phoneNo <", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoLessThanOrEqualTo(String value) {
            addCriterion("phoneNo <=", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoLike(String value) {
            addCriterion("phoneNo like", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoNotLike(String value) {
            addCriterion("phoneNo not like", value, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoIn(List<String> values) {
            addCriterion("phoneNo in", values, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoNotIn(List<String> values) {
            addCriterion("phoneNo not in", values, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoBetween(String value1, String value2) {
            addCriterion("phoneNo between", value1, value2, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPhonenoNotBetween(String value1, String value2) {
            addCriterion("phoneNo not between", value1, value2, "phoneno");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("startDate is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("startDate is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(Date value) {
            addCriterion("startDate =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(Date value) {
            addCriterion("startDate <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(Date value) {
            addCriterion("startDate >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(Date value) {
            addCriterion("startDate >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(Date value) {
            addCriterion("startDate <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(Date value) {
            addCriterion("startDate <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<Date> values) {
            addCriterion("startDate in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<Date> values) {
            addCriterion("startDate not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(Date value1, Date value2) {
            addCriterion("startDate between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(Date value1, Date value2) {
            addCriterion("startDate not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNull() {
            addCriterion("endDate is null");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNotNull() {
            addCriterion("endDate is not null");
            return (Criteria) this;
        }

        public Criteria andEnddateEqualTo(Date value) {
            addCriterion("endDate =", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotEqualTo(Date value) {
            addCriterion("endDate <>", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThan(Date value) {
            addCriterion("endDate >", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThanOrEqualTo(Date value) {
            addCriterion("endDate >=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThan(Date value) {
            addCriterion("endDate <", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThanOrEqualTo(Date value) {
            addCriterion("endDate <=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateIn(List<Date> values) {
            addCriterion("endDate in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotIn(List<Date> values) {
            addCriterion("endDate not in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateBetween(Date value1, Date value2) {
            addCriterion("endDate between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotBetween(Date value1, Date value2) {
            addCriterion("endDate not between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateIsNull() {
            addCriterion("SysCreateDate is null");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateIsNotNull() {
            addCriterion("SysCreateDate is not null");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateEqualTo(Date value) {
            addCriterion("SysCreateDate =", value, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateNotEqualTo(Date value) {
            addCriterion("SysCreateDate <>", value, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateGreaterThan(Date value) {
            addCriterion("SysCreateDate >", value, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("SysCreateDate >=", value, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateLessThan(Date value) {
            addCriterion("SysCreateDate <", value, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateLessThanOrEqualTo(Date value) {
            addCriterion("SysCreateDate <=", value, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateIn(List<Date> values) {
            addCriterion("SysCreateDate in", values, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateNotIn(List<Date> values) {
            addCriterion("SysCreateDate not in", values, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateBetween(Date value1, Date value2) {
            addCriterion("SysCreateDate between", value1, value2, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatedateNotBetween(Date value1, Date value2) {
            addCriterion("SysCreateDate not between", value1, value2, "syscreatedate");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyIsNull() {
            addCriterion("SysCreateBy is null");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyIsNotNull() {
            addCriterion("SysCreateBy is not null");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyEqualTo(String value) {
            addCriterion("SysCreateBy =", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyNotEqualTo(String value) {
            addCriterion("SysCreateBy <>", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyGreaterThan(String value) {
            addCriterion("SysCreateBy >", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyGreaterThanOrEqualTo(String value) {
            addCriterion("SysCreateBy >=", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyLessThan(String value) {
            addCriterion("SysCreateBy <", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyLessThanOrEqualTo(String value) {
            addCriterion("SysCreateBy <=", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyLike(String value) {
            addCriterion("SysCreateBy like", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyNotLike(String value) {
            addCriterion("SysCreateBy not like", value, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyIn(List<String> values) {
            addCriterion("SysCreateBy in", values, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyNotIn(List<String> values) {
            addCriterion("SysCreateBy not in", values, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyBetween(String value1, String value2) {
            addCriterion("SysCreateBy between", value1, value2, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSyscreatebyNotBetween(String value1, String value2) {
            addCriterion("SysCreateBy not between", value1, value2, "syscreateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateIsNull() {
            addCriterion("SysUpdateDate is null");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateIsNotNull() {
            addCriterion("SysUpdateDate is not null");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateEqualTo(Date value) {
            addCriterion("SysUpdateDate =", value, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateNotEqualTo(Date value) {
            addCriterion("SysUpdateDate <>", value, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateGreaterThan(Date value) {
            addCriterion("SysUpdateDate >", value, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("SysUpdateDate >=", value, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateLessThan(Date value) {
            addCriterion("SysUpdateDate <", value, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateLessThanOrEqualTo(Date value) {
            addCriterion("SysUpdateDate <=", value, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateIn(List<Date> values) {
            addCriterion("SysUpdateDate in", values, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateNotIn(List<Date> values) {
            addCriterion("SysUpdateDate not in", values, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateBetween(Date value1, Date value2) {
            addCriterion("SysUpdateDate between", value1, value2, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatedateNotBetween(Date value1, Date value2) {
            addCriterion("SysUpdateDate not between", value1, value2, "sysupdatedate");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyIsNull() {
            addCriterion("SysUpdateBy is null");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyIsNotNull() {
            addCriterion("SysUpdateBy is not null");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyEqualTo(String value) {
            addCriterion("SysUpdateBy =", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyNotEqualTo(String value) {
            addCriterion("SysUpdateBy <>", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyGreaterThan(String value) {
            addCriterion("SysUpdateBy >", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyGreaterThanOrEqualTo(String value) {
            addCriterion("SysUpdateBy >=", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyLessThan(String value) {
            addCriterion("SysUpdateBy <", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyLessThanOrEqualTo(String value) {
            addCriterion("SysUpdateBy <=", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyLike(String value) {
            addCriterion("SysUpdateBy like", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyNotLike(String value) {
            addCriterion("SysUpdateBy not like", value, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyIn(List<String> values) {
            addCriterion("SysUpdateBy in", values, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyNotIn(List<String> values) {
            addCriterion("SysUpdateBy not in", values, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyBetween(String value1, String value2) {
            addCriterion("SysUpdateBy between", value1, value2, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andSysupdatebyNotBetween(String value1, String value2) {
            addCriterion("SysUpdateBy not between", value1, value2, "sysupdateby");
            return (Criteria) this;
        }

        public Criteria andVersionnumIsNull() {
            addCriterion("VersionNum is null");
            return (Criteria) this;
        }

        public Criteria andVersionnumIsNotNull() {
            addCriterion("VersionNum is not null");
            return (Criteria) this;
        }

        public Criteria andVersionnumEqualTo(Integer value) {
            addCriterion("VersionNum =", value, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumNotEqualTo(Integer value) {
            addCriterion("VersionNum <>", value, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumGreaterThan(Integer value) {
            addCriterion("VersionNum >", value, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("VersionNum >=", value, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumLessThan(Integer value) {
            addCriterion("VersionNum <", value, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumLessThanOrEqualTo(Integer value) {
            addCriterion("VersionNum <=", value, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumIn(List<Integer> values) {
            addCriterion("VersionNum in", values, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumNotIn(List<Integer> values) {
            addCriterion("VersionNum not in", values, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumBetween(Integer value1, Integer value2) {
            addCriterion("VersionNum between", value1, value2, "versionnum");
            return (Criteria) this;
        }

        public Criteria andVersionnumNotBetween(Integer value1, Integer value2) {
            addCriterion("VersionNum not between", value1, value2, "versionnum");
            return (Criteria) this;
        }

        public Criteria andSysdelflagIsNull() {
            addCriterion("SysDelFlag is null");
            return (Criteria) this;
        }

        public Criteria andSysdelflagIsNotNull() {
            addCriterion("SysDelFlag is not null");
            return (Criteria) this;
        }

        public Criteria andSysdelflagEqualTo(String value) {
            addCriterion("SysDelFlag =", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagNotEqualTo(String value) {
            addCriterion("SysDelFlag <>", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagGreaterThan(String value) {
            addCriterion("SysDelFlag >", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagGreaterThanOrEqualTo(String value) {
            addCriterion("SysDelFlag >=", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagLessThan(String value) {
            addCriterion("SysDelFlag <", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagLessThanOrEqualTo(String value) {
            addCriterion("SysDelFlag <=", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagLike(String value) {
            addCriterion("SysDelFlag like", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagNotLike(String value) {
            addCriterion("SysDelFlag not like", value, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagIn(List<String> values) {
            addCriterion("SysDelFlag in", values, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagNotIn(List<String> values) {
            addCriterion("SysDelFlag not in", values, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagBetween(String value1, String value2) {
            addCriterion("SysDelFlag between", value1, value2, "sysdelflag");
            return (Criteria) this;
        }

        public Criteria andSysdelflagNotBetween(String value1, String value2) {
            addCriterion("SysDelFlag not between", value1, value2, "sysdelflag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 18 11:46:00 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_user
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}