package com.yyk.sz.zhzy.system.core.entity;

import java.util.Date;

public class SysUserAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin.userId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin.adminType
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String admintype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin.adminLevel
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String adminlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Date syscreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String syscreateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Date sysupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String sysupdateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Integer versionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String sysdelflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public SysUserAdmin(String uuid, String userid, String admintype, String adminlevel, Date syscreatedate, String syscreateby, Date sysupdatedate, String sysupdateby, Integer versionnum, String sysdelflag) {
        this.uuid = uuid;
        this.userid = userid;
        this.admintype = admintype;
        this.adminlevel = adminlevel;
        this.syscreatedate = syscreatedate;
        this.syscreateby = syscreateby;
        this.sysupdatedate = sysupdatedate;
        this.sysupdateby = sysupdateby;
        this.versionnum = versionnum;
        this.sysdelflag = sysdelflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public SysUserAdmin() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin.UUID
     *
     * @return the value of sys_user_admin.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin.UUID
     *
     * @param uuid the value for sys_user_admin.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin.userId
     *
     * @return the value of sys_user_admin.userId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin.userId
     *
     * @param userid the value for sys_user_admin.userId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin.adminType
     *
     * @return the value of sys_user_admin.adminType
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getAdmintype() {
        return admintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin.adminType
     *
     * @param admintype the value for sys_user_admin.adminType
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setAdmintype(String admintype) {
        this.admintype = admintype == null ? null : admintype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin.adminLevel
     *
     * @return the value of sys_user_admin.adminLevel
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getAdminlevel() {
        return adminlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin.adminLevel
     *
     * @param adminlevel the value for sys_user_admin.adminLevel
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setAdminlevel(String adminlevel) {
        this.adminlevel = adminlevel == null ? null : adminlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin.SysCreateDate
     *
     * @return the value of sys_user_admin.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Date getSyscreatedate() {
        return syscreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin.SysCreateDate
     *
     * @param syscreatedate the value for sys_user_admin.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSyscreatedate(Date syscreatedate) {
        this.syscreatedate = syscreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin.SysCreateBy
     *
     * @return the value of sys_user_admin.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSyscreateby() {
        return syscreateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin.SysCreateBy
     *
     * @param syscreateby the value for sys_user_admin.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSyscreateby(String syscreateby) {
        this.syscreateby = syscreateby == null ? null : syscreateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin.SysUpdateDate
     *
     * @return the value of sys_user_admin.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Date getSysupdatedate() {
        return sysupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin.SysUpdateDate
     *
     * @param sysupdatedate the value for sys_user_admin.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysupdatedate(Date sysupdatedate) {
        this.sysupdatedate = sysupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin.SysUpdateBy
     *
     * @return the value of sys_user_admin.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSysupdateby() {
        return sysupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin.SysUpdateBy
     *
     * @param sysupdateby the value for sys_user_admin.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysupdateby(String sysupdateby) {
        this.sysupdateby = sysupdateby == null ? null : sysupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin.VersionNum
     *
     * @return the value of sys_user_admin.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Integer getVersionnum() {
        return versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin.VersionNum
     *
     * @param versionnum the value for sys_user_admin.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setVersionnum(Integer versionnum) {
        this.versionnum = versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin.SysDelFlag
     *
     * @return the value of sys_user_admin.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSysdelflag() {
        return sysdelflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin.SysDelFlag
     *
     * @param sysdelflag the value for sys_user_admin.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysdelflag(String sysdelflag) {
        this.sysdelflag = sysdelflag == null ? null : sysdelflag.trim();
    }
}