package com.yyk.sz.zhzy.system.core.entity;

import java.util.Date;

public class SysUserAdminResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin_resource.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin_resource.adminId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin_resource.resourceId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin_resource.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Date syscreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin_resource.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String syscreateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin_resource.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Date sysupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin_resource.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String sysupdateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin_resource.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private Integer versionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_admin_resource.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    private String sysdelflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public SysUserAdminResource(String uuid, String adminid, String resourceid, Date syscreatedate, String syscreateby, Date sysupdatedate, String sysupdateby, Integer versionnum, String sysdelflag) {
        this.uuid = uuid;
        this.adminid = adminid;
        this.resourceid = resourceid;
        this.syscreatedate = syscreatedate;
        this.syscreateby = syscreateby;
        this.sysupdatedate = sysupdatedate;
        this.sysupdateby = sysupdateby;
        this.versionnum = versionnum;
        this.sysdelflag = sysdelflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public SysUserAdminResource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin_resource.UUID
     *
     * @return the value of sys_user_admin_resource.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin_resource.UUID
     *
     * @param uuid the value for sys_user_admin_resource.UUID
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin_resource.adminId
     *
     * @return the value of sys_user_admin_resource.adminId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin_resource.adminId
     *
     * @param adminid the value for sys_user_admin_resource.adminId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setAdminid(String adminid) {
        this.adminid = adminid == null ? null : adminid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin_resource.resourceId
     *
     * @return the value of sys_user_admin_resource.resourceId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin_resource.resourceId
     *
     * @param resourceid the value for sys_user_admin_resource.resourceId
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setResourceid(String resourceid) {
        this.resourceid = resourceid == null ? null : resourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin_resource.SysCreateDate
     *
     * @return the value of sys_user_admin_resource.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Date getSyscreatedate() {
        return syscreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin_resource.SysCreateDate
     *
     * @param syscreatedate the value for sys_user_admin_resource.SysCreateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSyscreatedate(Date syscreatedate) {
        this.syscreatedate = syscreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin_resource.SysCreateBy
     *
     * @return the value of sys_user_admin_resource.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSyscreateby() {
        return syscreateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin_resource.SysCreateBy
     *
     * @param syscreateby the value for sys_user_admin_resource.SysCreateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSyscreateby(String syscreateby) {
        this.syscreateby = syscreateby == null ? null : syscreateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin_resource.SysUpdateDate
     *
     * @return the value of sys_user_admin_resource.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Date getSysupdatedate() {
        return sysupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin_resource.SysUpdateDate
     *
     * @param sysupdatedate the value for sys_user_admin_resource.SysUpdateDate
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysupdatedate(Date sysupdatedate) {
        this.sysupdatedate = sysupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin_resource.SysUpdateBy
     *
     * @return the value of sys_user_admin_resource.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSysupdateby() {
        return sysupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin_resource.SysUpdateBy
     *
     * @param sysupdateby the value for sys_user_admin_resource.SysUpdateBy
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysupdateby(String sysupdateby) {
        this.sysupdateby = sysupdateby == null ? null : sysupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin_resource.VersionNum
     *
     * @return the value of sys_user_admin_resource.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public Integer getVersionnum() {
        return versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin_resource.VersionNum
     *
     * @param versionnum the value for sys_user_admin_resource.VersionNum
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setVersionnum(Integer versionnum) {
        this.versionnum = versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_admin_resource.SysDelFlag
     *
     * @return the value of sys_user_admin_resource.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public String getSysdelflag() {
        return sysdelflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_admin_resource.SysDelFlag
     *
     * @param sysdelflag the value for sys_user_admin_resource.SysDelFlag
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    public void setSysdelflag(String sysdelflag) {
        this.sysdelflag = sysdelflag == null ? null : sysdelflag.trim();
    }
}