package com.yyk.sz.zhzy.bbxt.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BBDoctorTreatmentAnalysis {

    private String mecidalnum;

    private Integer empbasicmainid;

    private String registrationnum;

    private String emname;

    private Integer emage;

    private String emaddress;

    private Boolean emsex;

    private String emsexname;

    private Date onsetdate;

    private String chinesemedicinecode;

    private String westernmedicinecode;

    private BigDecimal weight;

    private String dialecticalcode;

    private String curecode;

    private String usercode;

    private String username;

    private String deptcode;

    private String deptname;

    private String dialecticalname;

    private String curename;

    private String chinesemedicinename;

    private String westernmedicinename;

    private Integer outpatientcount;

    private BigDecimal herbalmoney;

    private BigDecimal acupuncturemoney;

    private BigDecimal westernmoney;

    private BigDecimal inspectionmoney;

    private BigDecimal checkmoney;

    private String DeptNum;
    private String SumZMoney;
    private String SumZJMoney;
    private String SumWMoney;
    private String SumCheckMoney;
    private String SumInspectionMoney;



    public BBDoctorTreatmentAnalysis() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.MecidalNum
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.MecidalNum
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getMecidalnum() {
        return mecidalnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.MecidalNum
     *
     * @param mecidalnum the value for CM_V_DoctorTreatmentAnalysis.MecidalNum
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setMecidalnum(String mecidalnum) {
        this.mecidalnum = mecidalnum == null ? null : mecidalnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.EmpBasicMainID
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.EmpBasicMainID
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public Integer getEmpbasicmainid() {
        return empbasicmainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.EmpBasicMainID
     *
     * @param empbasicmainid the value for CM_V_DoctorTreatmentAnalysis.EmpBasicMainID
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setEmpbasicmainid(Integer empbasicmainid) {
        this.empbasicmainid = empbasicmainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.RegistrationNum
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.RegistrationNum
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getRegistrationnum() {
        return registrationnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.RegistrationNum
     *
     * @param registrationnum the value for CM_V_DoctorTreatmentAnalysis.RegistrationNum
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setRegistrationnum(String registrationnum) {
        this.registrationnum = registrationnum == null ? null : registrationnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.EmName
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.EmName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getEmname() {
        return emname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.EmName
     *
     * @param emname the value for CM_V_DoctorTreatmentAnalysis.EmName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setEmname(String emname) {
        this.emname = emname == null ? null : emname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.EmAge
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.EmAge
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public Integer getEmage() {
        return emage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.EmAge
     *
     * @param emage the value for CM_V_DoctorTreatmentAnalysis.EmAge
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setEmage(Integer emage) {
        this.emage = emage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.EmAddress
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.EmAddress
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getEmaddress() {
        return emaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.EmAddress
     *
     * @param emaddress the value for CM_V_DoctorTreatmentAnalysis.EmAddress
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setEmaddress(String emaddress) {
        this.emaddress = emaddress == null ? null : emaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.EmSex
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.EmSex
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public Boolean getEmsex() {
        return emsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.EmSex
     *
     * @param emsex the value for CM_V_DoctorTreatmentAnalysis.EmSex
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setEmsex(Boolean emsex) {
        this.emsex = emsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.EmSexName
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.EmSexName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getEmsexname() {
        return emsexname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.EmSexName
     *
     * @param emsexname the value for CM_V_DoctorTreatmentAnalysis.EmSexName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setEmsexname(String emsexname) {
        this.emsexname = emsexname == null ? null : emsexname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.OnSetDate
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.OnSetDate
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public Date getOnsetdate() {
        return onsetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.OnSetDate
     *
     * @param onsetdate the value for CM_V_DoctorTreatmentAnalysis.OnSetDate
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setOnsetdate(Date onsetdate) {
        this.onsetdate = onsetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.ChineseMedicineCode
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.ChineseMedicineCode
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getChinesemedicinecode() {
        return chinesemedicinecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.ChineseMedicineCode
     *
     * @param chinesemedicinecode the value for CM_V_DoctorTreatmentAnalysis.ChineseMedicineCode
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setChinesemedicinecode(String chinesemedicinecode) {
        this.chinesemedicinecode = chinesemedicinecode == null ? null : chinesemedicinecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.WesternMedicineCode
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.WesternMedicineCode
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getWesternmedicinecode() {
        return westernmedicinecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.WesternMedicineCode
     *
     * @param westernmedicinecode the value for CM_V_DoctorTreatmentAnalysis.WesternMedicineCode
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setWesternmedicinecode(String westernmedicinecode) {
        this.westernmedicinecode = westernmedicinecode == null ? null : westernmedicinecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.Weight
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.Weight
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.Weight
     *
     * @param weight the value for CM_V_DoctorTreatmentAnalysis.Weight
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.DialecticalCode
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.DialecticalCode
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getDialecticalcode() {
        return dialecticalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.DialecticalCode
     *
     * @param dialecticalcode the value for CM_V_DoctorTreatmentAnalysis.DialecticalCode
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setDialecticalcode(String dialecticalcode) {
        this.dialecticalcode = dialecticalcode == null ? null : dialecticalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.CureCode
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.CureCode
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getCurecode() {
        return curecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.CureCode
     *
     * @param curecode the value for CM_V_DoctorTreatmentAnalysis.CureCode
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setCurecode(String curecode) {
        this.curecode = curecode == null ? null : curecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.UserCode
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.UserCode
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.UserCode
     *
     * @param usercode the value for CM_V_DoctorTreatmentAnalysis.UserCode
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.UserName
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.UserName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.UserName
     *
     * @param username the value for CM_V_DoctorTreatmentAnalysis.UserName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.DeptCode
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.DeptCode
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getDeptcode() {
        return deptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.DeptCode
     *
     * @param deptcode the value for CM_V_DoctorTreatmentAnalysis.DeptCode
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setDeptcode(String deptcode) {
        this.deptcode = deptcode == null ? null : deptcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.DeptName
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.DeptName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.DeptName
     *
     * @param deptname the value for CM_V_DoctorTreatmentAnalysis.DeptName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setDeptname(String deptname) {
        this.deptname = deptname == null ? null : deptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.DialecticalName
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.DialecticalName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getDialecticalname() {
        return dialecticalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.DialecticalName
     *
     * @param dialecticalname the value for CM_V_DoctorTreatmentAnalysis.DialecticalName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setDialecticalname(String dialecticalname) {
        this.dialecticalname = dialecticalname == null ? null : dialecticalname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.CureName
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.CureName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getCurename() {
        return curename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.CureName
     *
     * @param curename the value for CM_V_DoctorTreatmentAnalysis.CureName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setCurename(String curename) {
        this.curename = curename == null ? null : curename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.ChineseMedicineName
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.ChineseMedicineName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getChinesemedicinename() {
        return chinesemedicinename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.ChineseMedicineName
     *
     * @param chinesemedicinename the value for CM_V_DoctorTreatmentAnalysis.ChineseMedicineName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setChinesemedicinename(String chinesemedicinename) {
        this.chinesemedicinename = chinesemedicinename == null ? null : chinesemedicinename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.WesternMedicineName
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.WesternMedicineName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public String getWesternmedicinename() {
        return westernmedicinename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.WesternMedicineName
     *
     * @param westernmedicinename the value for CM_V_DoctorTreatmentAnalysis.WesternMedicineName
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setWesternmedicinename(String westernmedicinename) {
        this.westernmedicinename = westernmedicinename == null ? null : westernmedicinename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.OutpatientCount
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.OutpatientCount
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public Integer getOutpatientcount() {
        return outpatientcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.OutpatientCount
     *
     * @param outpatientcount the value for CM_V_DoctorTreatmentAnalysis.OutpatientCount
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setOutpatientcount(Integer outpatientcount) {
        this.outpatientcount = outpatientcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.HerbalMoney
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.HerbalMoney
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public BigDecimal getHerbalmoney() {
        return herbalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.HerbalMoney
     *
     * @param herbalmoney the value for CM_V_DoctorTreatmentAnalysis.HerbalMoney
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setHerbalmoney(BigDecimal herbalmoney) {
        this.herbalmoney = herbalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.AcupunctureMoney
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.AcupunctureMoney
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public BigDecimal getAcupuncturemoney() {
        return acupuncturemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.AcupunctureMoney
     *
     * @param acupuncturemoney the value for CM_V_DoctorTreatmentAnalysis.AcupunctureMoney
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setAcupuncturemoney(BigDecimal acupuncturemoney) {
        this.acupuncturemoney = acupuncturemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.WesternMoney
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.WesternMoney
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public BigDecimal getWesternmoney() {
        return westernmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.WesternMoney
     *
     * @param westernmoney the value for CM_V_DoctorTreatmentAnalysis.WesternMoney
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setWesternmoney(BigDecimal westernmoney) {
        this.westernmoney = westernmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.InspectionMoney
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.InspectionMoney
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public BigDecimal getInspectionmoney() {
        return inspectionmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.InspectionMoney
     *
     * @param inspectionmoney the value for CM_V_DoctorTreatmentAnalysis.InspectionMoney
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setInspectionmoney(BigDecimal inspectionmoney) {
        this.inspectionmoney = inspectionmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CM_V_DoctorTreatmentAnalysis.CheckMoney
     *
     * @return the value of CM_V_DoctorTreatmentAnalysis.CheckMoney
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public BigDecimal getCheckmoney() {
        return checkmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CM_V_DoctorTreatmentAnalysis.CheckMoney
     *
     * @param checkmoney the value for CM_V_DoctorTreatmentAnalysis.CheckMoney
     *
     * @mbggenerated Tue Dec 25 10:21:10 CST 2018
     */
    public void setCheckmoney(BigDecimal checkmoney) {
        this.checkmoney = checkmoney;
    }

    public String getDeptNum() {
        return DeptNum;
    }

    public void setDeptNum(String deptNum) {
        DeptNum = deptNum;
    }

    public String getSumZMoney() {
        return SumZMoney;
    }

    public void setSumZMoney(String sumZMoney) {
        SumZMoney = sumZMoney;
    }

    public String getSumZJMoney() {
        return SumZJMoney;
    }

    public void setSumZJMoney(String sumZJMoney) {
        SumZJMoney = sumZJMoney;
    }

    public String getSumWMoney() {
        return SumWMoney;
    }

    public void setSumWMoney(String sumWMoney) {
        SumWMoney = sumWMoney;
    }

    public String getSumCheckMoney() {
        return SumCheckMoney;
    }

    public void setSumCheckMoney(String sumCheckMoney) {
        SumCheckMoney = sumCheckMoney;
    }

    public String getSumInspectionMoney() {
        return SumInspectionMoney;
    }

    public void setSumInspectionMoney(String sumInspectionMoney) {
        SumInspectionMoney = sumInspectionMoney;
    }
}