package com.yyk.sz.zhzy.system.core.mapper;

import com.yyk.sz.zhzy.system.core.entity.GyUser;
import com.yyk.sz.zhzy.system.core.entity.GyUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Repository
@Component("qxUserMapper")
public interface GyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_User
     *
     * @mbggenerated Thu Dec 20 19:10:25 CST 2018
     */
    int countByExample(GyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_User
     *
     * @mbggenerated Thu Dec 20 19:10:25 CST 2018
     */
    int deleteByExample(GyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_User
     *
     * @mbggenerated Thu Dec 20 19:10:25 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_User
     *
     * @mbggenerated Thu Dec 20 19:10:25 CST 2018
     */
    int insert(GyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_User
     *
     * @mbggenerated Thu Dec 20 19:10:25 CST 2018
     */
    int insertSelective(GyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_User
     *
     * @mbggenerated Thu Dec 20 19:10:25 CST 2018
     */
    List<GyUser> selectByExample(GyUserExample example);

    List<GyUser> selectUser(GyUser gyUser);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_User
     *
     * @mbggenerated Thu Dec 20 19:10:25 CST 2018
     */
    GyUser selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_User
     *
     * @mbggenerated Thu Dec 20 19:10:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") GyUser record, @Param("example") GyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_User
     *
     * @mbggenerated Thu Dec 20 19:10:25 CST 2018
     */
    int updateByExample(@Param("record") GyUser record, @Param("example") GyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_User
     *
     * @mbggenerated Thu Dec 20 19:10:25 CST 2018
     */
    int updateByPrimaryKeySelective(GyUser record);

    int updateByUUID(GyUser gyUser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Gy_User
     *
     * @mbggenerated Thu Dec 20 19:10:25 CST 2018
     */
    int updateByPrimaryKey(GyUser record);

    List<GyUser> getAllUsers();

    int deleteByAccout(String usercode);
}