package com.yyk.sz.zhzy.system.core.mapper;

import com.yyk.sz.zhzy.system.core.entity.SysDatascope;
import com.yyk.sz.zhzy.system.core.entity.SysDatascopeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDatascopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_datascope
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int countByExample(SysDatascopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_datascope
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int deleteByExample(SysDatascopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_datascope
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_datascope
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int insert(SysDatascope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_datascope
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int insertSelective(SysDatascope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_datascope
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    List<SysDatascope> selectByExample(SysDatascopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_datascope
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    SysDatascope selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_datascope
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysDatascope record, @Param("example") SysDatascopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_datascope
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByExample(@Param("record") SysDatascope record, @Param("example") SysDatascopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_datascope
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByPrimaryKeySelective(SysDatascope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_datascope
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByPrimaryKey(SysDatascope record);
}