package com.yyk.sz.zhzy.system.core.mapper;

import com.yyk.sz.zhzy.system.core.entity.SysPost;
import com.yyk.sz.zhzy.system.core.entity.SysPostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int countByExample(SysPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int deleteByExample(SysPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int insert(SysPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int insertSelective(SysPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    List<SysPost> selectByExample(SysPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    SysPost selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysPost record, @Param("example") SysPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByExample(@Param("record") SysPost record, @Param("example") SysPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByPrimaryKeySelective(SysPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_post
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByPrimaryKey(SysPost record);
}