package com.yyk.sz.zhzy.system.core.mapper;

import com.yyk.sz.zhzy.system.core.entity.SysRoleCondition;
import com.yyk.sz.zhzy.system.core.entity.SysRoleConditionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleConditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_condition
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int countByExample(SysRoleConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_condition
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int deleteByExample(SysRoleConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_condition
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_condition
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int insert(SysRoleCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_condition
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int insertSelective(SysRoleCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_condition
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    List<SysRoleCondition> selectByExample(SysRoleConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_condition
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    SysRoleCondition selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_condition
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysRoleCondition record, @Param("example") SysRoleConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_condition
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByExample(@Param("record") SysRoleCondition record, @Param("example") SysRoleConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_condition
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByPrimaryKeySelective(SysRoleCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_condition
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByPrimaryKey(SysRoleCondition record);
}