package com.yyk.sz.zhzy.system.core.mapper;

import com.yyk.sz.zhzy.system.core.entity.SysUserAdminOrganization;
import com.yyk.sz.zhzy.system.core.entity.SysUserAdminOrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserAdminOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_organization
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int countByExample(SysUserAdminOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_organization
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int deleteByExample(SysUserAdminOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_organization
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_organization
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int insert(SysUserAdminOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_organization
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int insertSelective(SysUserAdminOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_organization
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    List<SysUserAdminOrganization> selectByExample(SysUserAdminOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_organization
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    SysUserAdminOrganization selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_organization
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysUserAdminOrganization record, @Param("example") SysUserAdminOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_organization
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByExample(@Param("record") SysUserAdminOrganization record, @Param("example") SysUserAdminOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_organization
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByPrimaryKeySelective(SysUserAdminOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_organization
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByPrimaryKey(SysUserAdminOrganization record);
}