package com.yyk.sz.zhzy.system.core.mapper;

import com.yyk.sz.zhzy.system.core.entity.SysUserAdminResource;
import com.yyk.sz.zhzy.system.core.entity.SysUserAdminResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserAdminResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int countByExample(SysUserAdminResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int deleteByExample(SysUserAdminResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int insert(SysUserAdminResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int insertSelective(SysUserAdminResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    List<SysUserAdminResource> selectByExample(SysUserAdminResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    SysUserAdminResource selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysUserAdminResource record, @Param("example") SysUserAdminResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByExample(@Param("record") SysUserAdminResource record, @Param("example") SysUserAdminResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByPrimaryKeySelective(SysUserAdminResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin_resource
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByPrimaryKey(SysUserAdminResource record);
}