package com.yyk.sz.zhzy.system.core.mapper;

import com.yyk.sz.zhzy.system.core.entity.SysUserAdmin;
import com.yyk.sz.zhzy.system.core.entity.SysUserAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int countByExample(SysUserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int deleteByExample(SysUserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int insert(SysUserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int insertSelective(SysUserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    List<SysUserAdmin> selectByExample(SysUserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    SysUserAdmin selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysUserAdmin record, @Param("example") SysUserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByExample(@Param("record") SysUserAdmin record, @Param("example") SysUserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByPrimaryKeySelective(SysUserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_admin
     *
     * @mbggenerated Tue Dec 18 11:46:00 CST 2018
     */
    int updateByPrimaryKey(SysUserAdmin record);
}